"""add reminded_at + timed_out_at to screening_session

Revision ID: e76c813663ae
Revises: d5f65a501975
Create Date: 2026-07-16 02:06:05.380176

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e76c813663ae'
down_revision: str | None = 'd5f65a501975'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screening_session', sa.Column('reminded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('screening_session', sa.Column('timed_out_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screening_session', 'timed_out_at')
    op.drop_column('screening_session', 'reminded_at')
    # ### end Alembic commands ###
